// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdaEgqBHHlk96GYIpKVS86-tF_qoViOzU',
    appId: '1:359598825804:web:a24d3d3cf38f4fe132efe9',
    messagingSenderId: '359598825804',
    projectId: 'socialapp-8799e',
    authDomain: 'socialapp-8799e.firebaseapp.com',
    storageBucket: 'socialapp-8799e.appspot.com',
    measurementId: 'G-Y23LJRN5X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN_xT1HLhnN3hX3TwnJPUG61mv7vVPGY4',
    appId: '1:359598825804:android:6eae224a3ec216ad32efe9',
    messagingSenderId: '359598825804',
    projectId: 'socialapp-8799e',
    storageBucket: 'socialapp-8799e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyBZU8ui9L710nIi5xqA9V-Ly_7uujp1s',
    appId: '1:359598825804:ios:b2d5fa3988c6b1c132efe9',
    messagingSenderId: '359598825804',
    projectId: 'socialapp-8799e',
    storageBucket: 'socialapp-8799e.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyBZU8ui9L710nIi5xqA9V-Ly_7uujp1s',
    appId: '1:359598825804:ios:7dc425c27ca5552032efe9',
    messagingSenderId: '359598825804',
    projectId: 'socialapp-8799e',
    storageBucket: 'socialapp-8799e.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
